### ISSUE TITLE
Suggestions are skipped when facet in source index contains special characers

### ISSUE THREAD

**Issue by britto** [algolia/algolia-popular-queries#11]
Given we have a source index named `albums` containing 3 albums, where we treat the `band` name as a facet. For example:

```json
[
   {
      "name" : "Sigh No More",
      "band" : "Mumford & Sons"
   },
   {
      "name" : "Slippery When Wet",
      "band" : "Bon Jovi"
   },
   {
      "band" : "The B-52's",
      "name" : "Rock Lobster"
   }
]
```

When we try to generate a suggestion index for it:

```json
{
   "indices" : [
      {
         "name" : "albums",
         "generate" : [
            ["band"]
         ]
      }
   ]
}
```

The band names containing special characters such as `&`, `'` and `+` won't become a suggestion, as expected:

```json
[
   {
      "query" : "bon jovi",
      "albums" : {
         "exact_nb_hits" : 1
      }
   }
]
```

Only the "clean" band names get indexed.

**Comment by Jerska** [comment]
Sorry for not answering here before.
We talked about it on our internal communication tools but didn't update here.

This is indeed expected, as per those two regexes:
https://github.com/algolia/query-suggestions/blob/eee676df2df7730d07b3a88a1b53ec3b6c0a8865/connector/src/search_string.rb#L2-L3

Those only allow for letters, accented letters, kanjis and numbers but not special characters.

There's a reason for this : symbols are ignored by the Algolia engine (treated as spaces).
As a result, you could have suggested queries with extra symbols inside, like
`The B-52's*#`.

I have a question for you : did you put those symbols in your `separatorsToIndex` ?
I'm thinking about this setting in the ranking tab of your index : 
![image](https://user-images.githubusercontent.com/5095856/41025015-197398e8-6971-11e8-8187-dc16bb7e9fbd.png)

Otherwise, would you be comfortable running this script on your own?
If the answer is yes, you can definitely modify those regexps to include the characters you want.

**Comment by britto** [comment]
Hi, @Jerska! Thanks for your reply.

> Did you put those symbols in your separatorsToIndex ?

Great catch. In fact, we have not used that option. I'm enabling it right now in our suggestions index and triggering a rebuild to see how it goes, will report back soon.

**Comment by Jerska** [comment]
I can already tell you that it won't change the end result today, as those regexps are hard coded.
However, we could maybe imagine including the `separatorsToIndex` in the list of allowed characters, hence my question. :)

**Comment by britto** [comment]
Hi, @Jerska. Sorry for the delay. Other issues came up over the past week so we had to address them before bringing new feedback.

The first issue is about capitalization, to our business keeping the suggestions in their original format is important, even though users don't type in query terms with proper capitalization very often. We were able to work around that by skipping the `downcase` call.

The second issue is a bit more complicated. We wanted to get _all_ facet values indexed as suggestions, regardless of count, but there is a [hard limit of 1k values](https://www.algolia.com/doc/api-reference/api-parameters/maxValuesPerFacet/) in that query. That means there is no way to get them all from the main index.

In the end we're left with two possible solutions for that:

1. Modify/extend the engine to accept punctuation and skip downcasing, then create a secondary source index, to use it as External Analytics, containing all the terms we want to index as suggestions. The downside is that the engine would need to run on our premises and we would also have to implement a recurrent task to keep that secondary index up to date.

2. Roll out our own custom recurrent task to do the job. It would fetch data straight from the database to the suggestions index, similar to what we have for the main index already. Then we would copy over the logic for updating popularity scores from Analytics data.

We're are still evaluating further tradeoffs in both alternatives. We'll keep you posted on our findings.

**Comment by Jerska** [comment]
You're definitely correct.

The 1K limit is unfortunately not something we can change.
This is however usually mitigated when you use combination of facets, e.g. `['brand', 'type']`, we'll only take the top 1000 brands, but each brand usually has way less than 1000 product types, so you could end up with way more than 1000 product types in the final suggestions.

Your first possible solution is the one I would have suggested you to do achieve your expected results.
Heroku w/ the scheduler add-on might be an easy and free way to host it and have it run periodically.
